# Dependencies
markdown:         Kramdown
highlighter:      rouge
plugins: 	        [jekyll-paginate]

# Setup
title:            Dr. Raphael Werner
description:      'Usability Engineer at Johner Institut'
url:              https://raphael-werner.github.io/
baseurl:          https://raphael-werner.github.io/


author:
  name:           'Raphael Werner'
paginate:         5
